### ISSUE TITLE
showing optional ports in `make init` if they are occupied

### ISSUE THREAD

**Issue by Jan-Piotraschke** [KAIZN-io/Voy#2]
It would make the `make init` setup more comfortable if the console shows whether a port is occupied and then suggests other available ports.

For example:
"Port 5000 is already in usage. Do you want to use port 5001 instead?"

**Comment by janlucaklees** [comment]
I would not want to implement too much Code for development purposes. All code is code that needs to be maintained.

You can configure the port in the `.env` file. And if not, I would suggest making it so. This way each project can just have it's port configured and you don't run into conflicts.
